CREATE SCHEMA LEILUM;

USE LEILUM;



CREATE TABLE IF NOT EXISTS LEILUM.TIPOUTILIZADOR (
	Tipo INT NOT NULL,
	Role VARCHAR(45) NOT NULL,
	PRIMARY KEY Tipo);


CREATE TABLE IF NOT EXISTS LEILUM.UTILIZADOR (
	Email VARCHAR(45) NOT NULL,
	Password VARCHAR(45) NOT NULL,
	TipoUtilizador INT NOT NULL,
	FOREIGN KEY TipoUtilizador REFERENCES LEILUM.TIPOUTILIZADOR Tipo,
	PRIMARY KEY Email);


CREATE TABLE IF NOT EXISTS LEILUM.INFO_UTILIZADOR (
	Contribuinte INT NOT NULL,
	Nome VARCHAR(45) NOT NULL,
	Morada VARCHAR(100) NOT NULL,
	Nacionalidade VARCHAR(45) NOT NULL,
	Contacto VARCHAR(45) NOT NULL,
	DataNascimento DATE NOT NULL,
	MetodoPagamento INT NOT NULL,
	Iban VARCHAR(45) NOT NULL,
	idUtilizador VARCHAR(45) NOT NULL,
	FOREIGN KEY (idUtilizador) REFERENCES UTILIZADOR (Email),
	PRIMARY KEY (Contribuinte));


CREATE TABLE IF NOT EXISTS LEILUM.LOTE (
	idLote INT NOT NULL,
	Comitente INT NOT NULL,
	Comprador INT NOT NULL,
	Avaliador INT NOT NULL,
	Imgpath VARCHAR(500) NOT NULL,
	FOREIGN KEY (Comitente) REFERENCES UTILIZADOR (Email),
	FOREIGN KEY (Comprador) REFERENCES UTILIZADOR (Email),
	FOREIGN KEY (Avaliador) REFERENCES UTILIZADOR (Email),
	PRIMARY KEY (idLote));
	

CREATE TABLE IF NOT EXISTS LEILUM.ARTIGO (
	idArtigo INT NOT NULL,
	Desiganacao VARCHAR(45) NOT NULL,
	Caracteristicas TEXT NOT NULL,
	Descricao TEXT NOT NULL,
	idLote INT NOT NULL,
	FOREIGN KEY (idLote) REFERENCES LOTE (idLote),
	PRIMARY KEY (idArtigo));


CREATE TABLE IF NOT EXISTS LEILUM.REGRA (
	idRegra INT NOT NULL,
	TempoMinimo TIME NOT NULL,
	TempoMaximo TIME NOT NULL,
	ValorMinimo DOUBLE(6,2),
	ValorMaximo DOUBLE(6,2),
	PRIMARY KEY (idRegra));


CREATE TABLE IF NOT EXISTS LEILUM.CATEGORIA (
	idCategoria INT NOT NULL,
	Designacao VARCHAR(45) NOT NULL,
	Regras INT NOT NULL,
	FOREIGN KEY (Regras) REFERENCES REGRA (idRegra),
	PRIMARY KEY (idCategoria));


CREATE TABLE IF NOT EXISTS LEILUM.LEILAO (
	idLeilao INT NOT NULL,
	Titulo VARCHAR(45) NOT NULL,
	Duracao TIME NOT NULL,
	ValorAbertura DOUBLE(6,2) NOT NULL,
	ValorBase DOUBLE(6,2) NOT NULL,
	ValorMinimo DOUBLE(6,2) NOT NULL,
	Estado INT NOT NULL,
	Avaliador INT NOT NULL,
	Comitente INT NOT NULL,
	Lote INT NOT NULL,
	Categoria INT NOT NULL,
	FOREIGN KEY (Avaliador) REFERENCES REGRA (Email),
	FOREIGN KEY (Comitente) REFERENCES REGRA (Email),
	FOREIGN KEY (Lote) REFERENCES REGRA (idLote),
	FOREIGN KEY (Categoria) REFERENCES REGRA (idCategoria),
	PRIMARY KEY (idLeilao));


CREATE TABLE IF NOT EXISTS LEILUM.LICITACAO (	
	idLicitacao INT NOT NULL,
	Valor DOUBLE(6,2) NOT NULL,
	Licitador INT NOT NULL,
	Leilao INT NOT NULL,
	FOREIGN KEY (Licitador) REFERENCES REGRA (Email),
	FOREIGN KEY (Leilao) REFERENCES REGRA (idLeilao),
	PRIMARY KEY (idLicitacao));












